name: monglish
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: ^3.5.4
 
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dartz:
  device_preview:
  dio:
  flutter_svg: ^2.0.16
  get:
  pretty_dio_logger:
  flutter_secure_storage: 
  another_flushbar: 
  animate_do: 

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^4.0.0


flutter_assets:
  assets_path: assets/images/
  output_path: lib/common/constants
  filename: app_images.dart
  field_prefix: null
  classname: AppImages


flutter:
  uses-material-design: true
 
  assets:
    - assets/images/

 
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500

 
